-- AlterTable
ALTER TABLE `User` ADD COLUMN `approved` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `role` ENUM('ADMIN', 'RECEPTIONIST', 'LAB_TECHNICIAN', 'ACCOUNTANT', 'PENDING') NOT NULL DEFAULT 'PENDING';
